In [2]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import os

In [3]:
conn = create_engine("mysql+pymysql://root:yash%402002@localhost/ecom_db")
print('Connected')

Connected

In [4]:
df = pd.read_sql_query('select * from data limit 10;',conn)
display(df)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom

In [10]:
df1 = pd.read_sql_table(table_name= 'data',con= conn)
df1.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [11]:
df1.shape

(541909, 8)

In [16]:
df1.dtypes

InvoiceNo      object
StockCode      object
Description    object
Quantity       object
InvoiceDate    object
UnitPrice      object
CustomerID     object
Country        object
dtype: object

In [17]:
df1.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [18]:
df1.duplicated().sum()

np.int64(5268)

In [19]:
df1.drop_duplicates(inplace= True)

In [20]:
df1.duplicated().sum()

np.int64(0)

In [22]:
df1['CustomerID'].value_counts().count()

np.int64(4372)

In [25]:
df1['Description'].value_counts().count()

np.int64(4223)

In [28]:
df1['Description'].isnull().sum()

np.int64(1454)

In [35]:
df2 = pd.read_sql_query('select * from data where Description is null and invoiceNo = 536414;',conn)
df2.head(50)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536414,22139,None,56,12/1/2010 11:52,0.0,None,United Kingdom

In [49]:
(df1['InvoiceNo'].value_counts() == 1).sum()

np.int64(5847)

In [50]:
(df1['InvoiceNo'].value_counts() != 1).sum()

np.int64(20053)

In [51]:
df1.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135037
Country             0
dtype: int64

In [52]:
(df1['Description'].value_counts() == 1).sum()

np.int64(308)

In [53]:
(df1['Description'].value_counts() != 1).sum()

np.int64(3915)

In [54]:
(df1[['Description','InvoiceNo']].value_counts() == 1).sum()

np.int64(524213)

In [55]:
(df1[['Description','InvoiceNo']].value_counts() != 1).sum()

np.int64(5373)

In [56]:
(df1[['CustomerID','InvoiceNo']].value_counts() == 1).sum()

np.int64(3400)

In [57]:
(df1[['CustomerID','InvoiceNo']].value_counts() != 1).sum()

np.int64(18790)

In [60]:
drop_customerID = df1.dropna(subset = ['CustomerID'],inplace= True)
drop_Description = df1.dropna(subset = ['Description'],inplace= True)

In [61]:
df1.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [63]:
df1.dtypes

InvoiceNo      object
StockCode      object
Description    object
Quantity       object
InvoiceDate    object
UnitPrice      object
CustomerID     object
Country        object
dtype: object

In [69]:
rm_space_tails = df1.apply(lambda col: col.str.strip() if col.dtype == "object" else col)

#### `Understanding r"\s+"`
- r → Raw string (so backslashes are treated literally)
- \s → Matches any whitespace character, including:
- space ( )
- tab (\t)
- newline (\n)
- '+' → Means one or more

In [70]:
df1["Description"] = df1["Description"].str.replace(r"\s+", " ", regex=True).str.strip()

In [71]:
df1.columns = df1.columns.str.strip()

In [72]:
df1["StockCode"] = df1["StockCode"].str.replace(" ", "")

In [73]:
df1.dtypes

InvoiceNo      object
StockCode      object
Description    object
Quantity       object
InvoiceDate    object
UnitPrice      object
CustomerID     object
Country        object
dtype: object

In [81]:
df1['CustomerID'] = pd.to_numeric(df1['CustomerID'], errors='coerce')

In [107]:
df1['UnitPrice'] = pd.to_numeric(df1['UnitPrice'], errors='coerce')

In [118]:
df1['InvoiceDate'] = pd.to_datetime(df1['InvoiceDate'],errors='coerce')

In [119]:
datatype = df1.astype({'Quantity' : 'int',
                      'UnitPrice' : 'float',
                      'CustomerID' : 'Int64'})

In [120]:
# add total price
df1['TotalPrice'] = round(df1['Quantity'] * df1['UnitPrice'],2)

In [121]:
df1.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [122]:
df1.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
TotalPrice            float64
dtype: object

In [123]:
print(f"{'-'*50} Verifying Data {'-'*65}\n")
print("-"*131)
print(f"\n{'-'*60} Info Data {'-'*60}\n")
display(df1.info())
print(f"\n{'-'*50} Checking Null Data {'-'*60}\n")
display(df1.isnull().sum())
print(f"\n{'-'*60} Head Data {'-'*60}\n")
display(df1.head())
print("-"*131)

-------------------------------------------------- Verifying Data -----------------------------------------------------------------

-----------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------ Info Data ------------------------------------------------------------

<class 'pandas.core.frame.DataFrame'>
Index: 401604 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    401604 non-null  object
 1   StockCode    401604 non-null  object
 2   Description  401604 non-null  object
 3   Quantity     401604 non-null  int64
 4   InvoiceDate  401604 non-null  datetime64[ns]
 5   UnitPrice    401604 non-null  float64
 6   CustomerID   401604 non-null  float64
 7   Country      401604 non-null  object
 8   TotalPrice   401604 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 30.6+ MB

None

-------------------------------------------------- Checking Null Data ------------------------------------------------------------

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
TotalPrice     0
dtype: int64

------------------------------------------------------------ Head Data ------------------------------------------------------------

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

-----------------------------------------------------------------------------------------------------------------------------------

In [124]:
# exporting the clean data back to sql
export = df1.to_sql('data_cleaned',
          conn,
          if_exists = 'replace',
          index = False)

In [126]:
export_csv = df1.to_csv('data_cleaned.csv',index = False)